### ISSUE TITLE
License

### ISSUE THREAD

**Issue by clbarnes** [gleb-shtengel/FIBSEM_gs_py#1]
Could you add a license to this repository? I'd like to contribute to it but that's not advisable without a license.

**Comment by gleb-shtengel** [comment]
Hi Chris,
Sorry, I am new to this git-hub licensing field. I will look into this, but
it may take few days.
Gleb

**Comment by clbarnes** [comment]
Thanks! I think all that needs to happen is pasting something like [this text](https://choosealicense.com/licenses/mit/) (replacing `[year]` and `[name]`) into a file called `LICENSE` in the root of the repo. More licenses and their use cases can be found here: https://choosealicense.com/

**Comment by gleb-shtengel** [comment]
Added a license.txt file.
